# Gunakan image dasar PHP yang sesuai
FROM php:8.1-apache

# Install ekstensi yang dibutuhkan
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Copy file aplikasi
COPY . /var/www/html

# Konfigurasi Apache
RUN a2enmod rewrite

# Expose port 8080
EXPOSE 8080

# Perintah untuk menjalankan Apache
CMD ["apache2-foreground"]