FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    tcpdump \
    net-tools \
    iputils-ping

COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY monitor_traffic.py .

EXPOSE 5000

CMD ["python3", "monitor_traffic.py"]